Laravel-Lang/lang

sc/reminders.php
sc/validation.php

Just 2 updates to sardinian translation

Sardinian update

---

ru/validation.php

I omitted translation for 'valid' as it sounds (IMHO) better without it.

RU JSON translation

---

nl/validation.php

The max translations stated ':attribute must be less than :max'. This is incorrect as it should be 'can't be more than :max'.

Fix dutch 'max' translations

---

.idea/vagrant.xml
hr/auth.php

This correction added a correct Croatian translation
instead of the english ones that were in the auth.php script.
Users of this code will therefore not have to change/modify
these manually as they are already correct.
This prevents from showing unwanted translations and
enhances the user experience.

Added Translation to hr/auth.php

---

README.md

Translations moved from app to resources in Laravel 5

Corrected link to en translations for Laravel 5

---

fr/auth.php

Hi,
"identifiants" is the correct word for this situation.

Correct a wrong word

---

nl/validation.php

Clear translation of 'characters'. Where 'karakters' is used before, 'karakters' should be used here too in stead of 'characters'.

Clear translation of 'characters'.

---

nl/validation.php

The Dutch phrase is confusing, it will say:
``admin password is verplicht tenzij rol voorkomt in admin, moderator``
(``admin password is required unless role occurs in admin, moderator``)
Whereas this makes more sense:
``admin password is verplicht tenzij rol gelijk is aan admin, moderator``
(``admin password is required unless role is equal to admin, moderator``)

Changed confusing Dutch phrasing for required_unless

---

es/passwords.php

Hi,
I would like to contribute with a better spanish language line for password.sent.
I think that the current spanish translation for this line is not accurate and lacks of some detail and context.
English original line states:
"We have e-mailed your password reset link!"
It says that an email was sent with a password reset link, this makes sense to the user viewing this message.
The current spanish translation in english states:
"Password reminder sent!"
It lacks of context and makes me feel like i'm interacting with a robot.
The proposed line in spanish makes the user feel like a person is in the other side. :)
Thanks!

Change the spanish password reminder sent language line for a more readable

---

src/zh-CN/validation.php

update zh-CN validation.php wrong word. @overtrue 有个错别字

update zh-CN validation.php wrong word

---

src/nl/auth.php

'Gefaalde' is not a common word for failed in internet/website language for Dutch 'mislukte' is better

more common dutch

---

src/fr/validation.php

The existing translation is saying that the value should be bigger then `:min`
I added the part when it says that it could be equal to `:min`

Fix 'min' validation rule for French

---

src/nl/validation.php

In Dutch, 'liggend streepje' is a dash, see https://nl.wikipedia.org/wiki/Liggend_streepje_(leesteken).
I think it is common to just use 'underscore' in Dutch (https://nl.wikipedia.org/wiki/Underscore).

Fix Dutch 'underscore' translation

---

src/de/validation.php

"Umlaute (ä, ö, ü) und Eszett (ß) sind nicht erlaubt."
They are valid in Laravel 5.4:
https://github.com/illuminate/validation/blob/5.4/Concerns/ValidatesAttributes.php#L243

[de] Removed old text for validation.alpha_dash

---

src/ca/validation.php

Reference: https://community.languagetool.org/rule/show/DIRECCIO_ADRECA?lang=ca&subId=2

Corrected the translation "address" to Catalan

---

src/tr/passwords.php

"Şifre" actually means "cipher" (as in encryption) in Turkish, "parola" is the correct translation of "password"

şifre değil parola

---

src/nb/validation.php

If I translate the current Norwegian max-rule for strings back to English, it reads:
```:attribute must not be shorter than :max characters```
... which is the exact opposite of what this validation error text is meant to convey. After the change, it will translate to:
```:attribute must not be greater than :max characters```

[nb] Max-rule for files is wrong

---

src/de-CH/auth.php
src/de-CH/pagination.php
src/de-CH/passwords.php
src/de-CH/validation.php

The Swiss do not use "ß". This PR creates a new language and replaces ß with 'ss'.
For reference: https://en.wikipedia.org/wiki/%C3%9F#Switzerland_and_Liechtenstein
**Attention**: Although it would be funny, this is NOT swiss-german. This is just the localized version of German for Switzerland, thus de-CH.

[de-CH] Add Swiss standard German 

---

src/nl/validation.php

'tekenreeks' is very uncommonly used and will likely confuse users. 'tekst' on the other hand is a more common phrase to refer to text. 
Signed-off-by: MegaXLR <admin@megaxlr.net>

[NL] Use more common word "tekst" for string

---

README.md

The current image looks like this:
Corrected like this:
[![Stories in Ready](https://badge.waffle.io/caouecs/Laravel-lang.svg)](http://waffle.io/caouecs/Laravel-lang)

Fixed link to badge

---

src/ar/validation.php

Taylor makes every line of a block comment 3 characters less than the previous line. This change is a copy-paste from his comments in the English version.

update comment to match Taylor's style

---

src/ar/validation.php

A grammatical rule requires the predicate (khabar) of "kaan" to be in the accusative case (mansoob). Thus, the ending "yaa + noon" for the dual is expected rather than the current "alif + noon."

fix grammar error in predicate of kaan - AR

---

json/es.json

Hi,
there should not be any space between
```
[:actionURL] (:actionURL)
```
Markdown parser is not considering it a link when there is a space.

Fix: markdown link should not have any space

---

json/nl.json

The Dutch json file did not contain a translation for the 403 error message. This fixes it

[nl] Add 403 Dutch translation

---

src/pl/passwords.php

The default required length for the password is eight digits as of Laravel 5.8.0.

[pl] Update the password string

---

src/vi/passwords.php

The default required length for the password is eight digits as of Laravel 5.8.0.

[VI] Update the password string

---

src/nl/validation.php

The validation message said ':attribute has to be **no** valid URL'.
That is incorrect and will be solved by this pull request.

[nl] Fix incorrect Dutch url validation message

---

src/ru/validation.php

This pull request contains a commit fixing the typo in Russian `date_equals` field.

[ru] Fix typo in date_equals field

---

src/lt/pagination.php

According to Lithuanian language rules word "sekantis" can not be used in pagination context.
References:
- http://www.vlkk.lt/konsultacijos/2710-sekantis
- http://zemynosgimnazija.lt/kalbekime_taisyklingai/sekantis_kitas.pdf

Modify Lithuanian pagination translation

---

src/id/validation.php

Hi,
This PR add translation for `ends_with` and changes some translations to make it more native.

[id] Add validation for ends_with & general grammatical changes in validation

---

src/ar/validation.php

The old translation was not clear this what is says
`:attribute exists`
I changed to the equivalent of the original laravel translation which says
`The selected :attribute is invalid.`

[ar] Update validation.not_in

---

src/es/validation.php

"terms" is commonly used for referencing terms of service and similars.

[es] Adding a commonly used attribute (terms)

---

src/sv/validation.php

This makes the after and before validation messages work equally well with dates and fields, just as the english variant.

SV: Make date validation messages also work with fields

---

json/es.json

This translation didn't work after updating to Laravel 7.0.*

Fix translation in es.json, translation wasn´t work in mail subcopy

---

json/ru.json

Incorrect translation: "A fresh verification link has been sent to your email address."

[Ru] Fix "A fresh verification link" translation

---

src/hu/validation.php

Hi,
Currently, the validation message for the "exists" rule is wrong in hungarian.
The original message is: "The selected :attribute is invalid."
The current translation means: "The :attribute exists."
Correctly, it should be "A kiválasztott :attribute érvénytelen."
"kiválasztott" means selected
"érvénytelen" means invalid

[hu] Fix exists validation message

---

.github/workflows/make-todo.yml
script/todo.php

Recently, I have been seeing a problem with the todo.md file conflict.
I propose a solution to the problem: when creating a PR, developers DO NOT add the todo.md file to it.
When a PR is accepted into the master branch, the "GitHub Action" is launched, which itself generates this file and pushes to master.
All you need to do in this repository is to check if GitHub Actions are enabled.
For example,
If the developer adds a modified todo.md file to the PR, then it's okay. There will be two options:
1. If there is no PR conflict, then it can be accepted;
2. If there is a conflict, the developer will have to solve it.
In any case, the file will be automatically updated when a PR is merged or a push to the master branch.

Auto-make todo.md

---

json/sl.json
script/excludes/sl.php

'Email' changed to 'Elektronski naslov' (both are ok in sl)
Added 'Administrator' to exclusion list
'todo' file has to be updated by somebody else. Thank you.

[sl] Updated 2 missing translations

---

json/es.json
script/en/en.json

I made a [Pull Request](https://github.com/laravel/jetstream/pull/625) to [Laravel Jetstream](https://github.com/laravel/jetstream) in order to *Make the subject of the team invitation email translatable* which was ***merged***.
- [Team Invitation](https://github.com/laravel/jetstream/blob/2.x/src/Mail/TeamInvitation.php#L42)

[en, es] Translate subject of Team Invitation email

---

json/es.json

I added this tag for possible backward compatibility with Laravel Jetstream (version < 2) and for not damaging the _completion status_ of the Spanish language. But I must clarify that this tag doesn't exist in **Laravel Jetstream** v2, it [was removed](https://github.com/laravel/jetstream/commit/af723fc14c8afa3a5b5a9ebbf7b78948a907ef27#diff-3b7a681602096a9164ff064b9d2777ce4eaf2c5848198ab1effea9c22f67bad6) on October 21 of 2020.

[es] Add tag for retrocompatibility

---

script/en/validation-inline.php
script/en/validation.php
src/tr/validation-inline.php
src/tr/validation.php

laravel/framework#36667
laravel/docs#6931
laravel/laravel#5569

[tr] Add prohibited validation rule

---

.github/workflows/self-update.yml
app/excludes.php
app/main/Concerns/Contains.php
app/main/Concerns/Storable.php
app/main/Contracts/Filesystem.php
app/main/Processors/Excludes.php
app/main/Processors/Processor.php
app/main/Processors/Statuses/Processor.php
app/main/Services/Filesystem/Base.php
app/main/Services/Filesystem/Json.php
app/main/Services/Filesystem/Markdown.php
app/main/Services/Filesystem/Php.php
app/resources/arrays/auth.stub
app/resources/arrays/exclude.stub
app/resources/arrays/pagination.stub
app/resources/arrays/passwords.stub
app/resources/arrays/validation-inline.stub
app/resources/arrays/validation.stub
composer.json

* Added check of exclusion files for keys relevance
* Added templates for saving files
Before > After:
> Excludes file
>
> ![image](https://user-images.githubusercontent.com/10347617/114277104-7eb89380-9a32-11eb-8e23-e70463c33447.png)
> Locale's file
>
> ![image](https://user-images.githubusercontent.com/10347617/114277140-a7408d80-9a32-11eb-935b-688753b13f52.png)
What problems have been solved:
1. Duplicate keys were specified in some exclusion files;
2. There was no sorting in the exclusion files;
3. Some keys were excluded from the main files.
What's happening:
1. Values are sorted alphabetically;
2. Keys deleted from EN files are excluded (both php and json files are checked);
3. A comment is inserted at the beginning of each file.
Also, when processing translation files, a comment is …

Added check of exclusion files for keys relevance

---

app/tests/PhpTest.php
app/tests/TestCase.php

I've noticed that some people use `:Attribute` rather than `:attribute` at the beginning of a sentence (for example: [here](https://github.com/Laravel-Lang/lang/pull/1615/files#diff-0ecf1116fcf054e48b4f8a53c508f460bb59310aac195515c515f4f6613661fbL90-L104), [here](https://github.com/Laravel-Lang/lang/pull/1616/files#diff-0ecf1116fcf054e48b4f8a53c508f460bb59310aac195515c515f4f6613661fbL20-L106)). Since the tests are case sensitive, they do not consider `:Attribute` an error. Therefore, I added such a variant of the word spelling when checking the `validation-inline.php` file.
**Before:**
**After:**

Added check for ":Attribute" when running tests

---

locales/fr/fr.json

Hey!
"Avec les mis en corbeille" is just not a valid sentence, by any means regardless of the context.

[fr] fix bad wording

---

.github/workflows/self-update.yml

For some reason unknown to me, GitHub Actions strips the special characters from the commit header, forming a header like `Updating the file`.

Removed special characters from the commit header

---

locales/es/validation-inline.php
locales/es/validation.php
source/validation-inline.php
source/validation.php

[This rule](https://github.com/laravel/laravel/blob/8.x/resources/lang/en/validation.php#L34) will replace the rule `password` in the next major version of Laravel.
- [https://github.com/laravel/laravel/pull/5628](https://github.com/laravel/laravel/pull/5628)

[en, es] Add validation.current_password rule

---

composer.json

The tests return an error because https://github.com/Laravel-Lang/lang/pull/1943 no has been accepted. He corrects this error.

Fixed Class "LaravelLang\Publisher\Concerns\BaseServiceProvider" not found

---

.github/workflows/update.yml

This is necessary in order to automatically maintain the relevance of automatically scanned projects.

Added rule to automatically self-update

---

locales/tr/tr.json

This PR adds the missing translations in [`tr.json`](https://github.com/Laravel-Lang/lang/blob/main/locales/tr/tr.json#L613):
- "This coupon code can only be used by new customers."

[tr] Add missing translations

---

locales/ja/ja.json

- related issue: https://github.com/Laravel-Lang/lang/issues/1226
- related commit: https://github.com/Laravel-Lang/lang/commit/72cec64bc9524af2f3cc390590c6b95f1de05057
- I think he accidentally forgot to erase one of the two \[:displayableActionUrl\](:actionURL) in ja.json

[ja] delete [:displayableActionUrl](:actionURL)

---

locales/nl/validation.php

* `date_format` was missing `:format`.
* `enum` was not compatible with all word genders:
* ❌  "De geselecteerde _formaat_ is ongeldig."
* ✅  "[het] Gekozen _formaat_ is ongeldig."
* ✅  "[de] Gekozen _dag van de week_ is ongeldig."
* `uuid`: "de UUID" -> "een geldig**e** UUID" (https://taaladvies.net/wel-of-geen-e-achter-een-bijvoeglijk-naamwoord-algemeen/#3)

[nl] Update validation.php

---

locales/fr/validation.php

The updated translation for 'min' was saying `File size should be greater then :min` This PR adds `ou égale` which means `or equal`

[fr] Add equality to the sentence

---

.github/workflows/phpunit.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: nathannaveen <42319948+nathannaveen@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

locales/pt_BR/pt_BR.json

"Camarão" in english means shrimp, the correct name of Cameroon in portuguese is Camarões.
even in Brazilian portuguese

Correct the Cameroon country name in  portuguese

---

locales/pt/pt.json

"Camarão" in english means shrimp, the correct name of Cameroon in portuguese is Camarões.

Correct the Cameroon country name in portuguese

---

locales/ro/json.json

In romanian **Andorra** is `Andorra`

[ro]: Fix translation

---

locales/nl/php.json

[nl]: Remove misplaced space in 'datalek'

---

locales/fr/php.json

Added "de" where appropriate to be coherent with the max and size rules.

[fr]: Missing "de" in the "minimum" of type String rule

---

locales/fr/php-inline.json

'Mot de passe' is masculine.
```diff
-Le mot de passe est apparue (...)
+Le mot de passe est apparu (...)
```

[fr]: Fix typo

---

locales/nl/php-inline.json
locales/nl/php.json

First validation key which references the reader with "je", but I think it's necessary as "onbevoegde/ongeautoriseerde waarde" would not scan as normal Dutch and would lower comprehensibility.

[nl]: Translated new keys

---

locales/uk/_excludes.json
locales/uk/json.json

@Oleksandr-Moik, привіт! Можеш перевірити ПР?
Побачив що пара фраз [світиться](https://laravel-lang.com/statuses/lang/statuses/uk.html) в неперекладених. "API" додав у винятки перекладу як і в російській мові, а "N/A" переклав.
Чи все правильно?

[uk]: Translations have been updated

---

locales/th/json.json

Change "Thailand" translation from "ประเทศไทย" to "ไทย".
Based on the translation of other country names, like:
```json
"Tajikistan": "ทาจีกิสถาน",
"Tanzania": "แทนซาเนีย",
"Tanzania, United Republic of": "แทนซาเนีย, สหสาธารณรัฐ",
```
They don't include the prefix "ประเทศ" ("country") in their translation.
So the translation of "Thailand" should not include "ประเทศ" as well.
This will make it consistent for the user and make it easier to find country names when sorted alphabetically (with a locale-aware collator).

[th]: Update json.json: "Thailand": "ประเทศไทย" -> "ไทย"

---

locales/es/json.json

This translation often describes an action but **Vista** is not an action!

[es]: Update json.json

---

locales/de/php.json

"Passworterinnerung" is wrong, it means password remember and not password reset

[de]: Fix password.sent translation

---

source/framework/extended.json

In one of my projects I found that the string `'This action is unauthorized.'` is not translated but it has translation support within the framework. To obtain its translation, just add it to the `.json` and translate it.
This message is visible in the error template when an authorization exception is thrown.
Support for translation is not direct. Let's see where it is ...
if you throw an `Illuminate\Auth\Access\AuthorizationException` the template `.../Illuminate/Foundation/Exceptions/views/403.blade.php` is rendered.
```php
@extends('errors::minimal')
@section('title', __('Forbidden'))
@section('code', '403')
@section('message', __($exception->getMessage() ?: 'Forbidden'))
```
in the [Line 5](https://github.com/laravel/framework/blob/11.x/src/Illuminate/Foundation/Exceptions/views/403.bl …

[source]: Add missing extended translation to framework.

---

locales/el/php-inline.json
locales/el/php.json

Translation added for the following keys:
- required_if_declined

[el]: Added translations to new key

---

locales/nb/json.json

Fixing a typo: Changing 'Profil informasjon' to 'Profilinformasjon' to align with correct Norwegian spelling.

[nb]: Fix typo in Norwegian Bokmål

---

locales/bg/json.json

The difference is in one word, but that makes a difference in important words such as "Save". 
Proof of correctness: https://translate.google.com/?sl=bg&tl=en&text=%D0%97%D0%B0%D0%BF%D0%B0%D0%B7%D0%B8&op=translate 
ps: Thanks for making and maintaining this package!

[bg]: Update incorrect translated word

---

locales/ko/json.json

I found the wrong translate value, so I have made PR.
File : /locales/ko/json.json
```diff
-    "Replicate": "뒤로 젖히다",
+    "Replicate": "복제하기",
```
Would you please merge it soon?
Thank you for helping me in advance.

[ko]: Fix wrong translation value for contains key

---

locales/ko/json.json

The English word "view" can function as both a verb and a noun, but in Korean, these meanings should be distinguished.
I suggest the following change:
```diff
- "View": "뷰",
+ "View": "보기",
```
In Korean, "뷰" is commonly used to refer to a sight, landscape, or scene, rather than the act of looking or seeing. To better reflect the intended meaning, "보기" would be a more appropriate translation.
I believe no Korean would understand the image above - "뷰".
Reference link - https://nova.laravel.com/docs/v4/resources/fields#tag-field

[ko]: Translate the word `View` more correctly.

---

locales/bg/json.json

The parameter in the translated string was actiontext instead of actionText.

[bg]: Fix string parameter not being displayed

---

locales/ja/json.json

``` before
"Mali": "小さい"
```
```after
"Mali": "マリ"
```
I made this change because, judging from the surrounding context, it seems that "Mali" is referring to the country rather than the adjective meaning "small" in Croatian or other Slavic languages.
However, if this key was intentionally translated to mean "small" in another language, please feel free to close this PR. I would appreciate your clarification in that case.
Thank you for your time and consideration.

[ja]: Fix Typo in Japanese

---

locales/es/json.json

- Updated `"Click to choose"` translation from `"Haga click para elegir"` to `"Haga clic para elegir"`.
- **Linguistic correctness**: “clic” is the standard term in Spanish for a mouse click.
- **Consistency**: Aligns with other UI translations that follow RAE spelling.
- **Improved localisation quality**: Ensures correct and professional presentation in Spanish interfaces.

[es]: Fix Spanish translation for "Click to choose" (click → clic)
