Laravel-Lang/lang

sc/passwords.php
sc/validation.php

Some fixes for Sardinian in Laravel5

Laravel5 Sardinian fixs

---

zh-CN/validation.php
zh-HK/validation.php

update validation.php in zh-CN and zh-HK, fix the translation error about 'exist'

update validation.php in zh-CN and zh-HK, fix the translation error about 'exist'

---

zh-CN/validation.php
zh-HK/validation.php

update 'exists' translation

---

sl/pagination.php
sl/reminders.php
sl/validation.php

Adds initial slovenian language pack.

Slovenia lang

---

sl/pagination.php
sl/passwords.php
sl/reminders.php
sl/validation.php

Adds sl lang support for laravel5.

Laravel 5 sl-lang

---

sv/passwords.php

Update swedish reminders

---

es/reminders.php

I think "Tu" is more friendly than "Su", it sounds too formal.

Spanish-friendly transaltion

---

hr/pagination.php
hr/reminders.php
hr/validation.php

Translated Laravel 4 messages.

Initial Croatian translation.

---

README.md

updated language location for laravel 5

---

nl/validation.php

i noticed that the fr/validation.php also has these, and they are quite useful...

added some common attributes to validation.php

---

nl/passwords.php

"token" had a grammar problem.

Fix grammar

---

nl/validation.php

fixed nl/Dutch translation for 'string'

---

da/auth.php
da/passwords.php

I have updated the translations of the strings into danish and corrected a few strings that were not translated properly.

Updated the danish (da) translations

---

id/auth.php
id/validation.php

Translation for auth.php and validation.string

Indonesian translation

---

it/auth.php
it/validation.php

- Fixed indentation (like original Laravel file)
- Used ' for array keys but not for values ( to allow apostrophe )
- Fixed some translations (max, min, size, string and url)

Fixed Italian file format and minor improvements

---

it/validation.php

Breaking the php artisan translations:import command

Forgotten commas in IT language fix

---

ko/auth.php

added the korean translation to auth.php

transalation korean auth messages.

---

nl/validation.php

Changed 'format' to 'formaat' in the regex validation string.

Corrected 'format' to 'formaat'

---

Source.md
Status.md

Update Japanese status.

---

ar/auth.php
ar/validation.php

Translate some sentences from English into Arabic

---

nb/auth.php

Norsk Bokmål (Norwegian) translation.

Translated nb/auth.php

---

.gitignore
.php_cs

Related to this issue: https://github.com/caouecs/Laravel-lang/issues/460

Double arrow align and enabled PHP-CS-Fixer Cache

---

README.md

The readme is wrong about the name of the field in `app.php` that we need to edit.

Readme: language -> locale

---

es/validation.php

Add spanish attributes the validation.php file.

Update es\validation.php with custom attributes.

---

ka/validation.php

One of the lines in validation.php wasn't translated before.

Add Georgian translation line

---

pt-BR/validation.php

Fixed error in the Brazilian portuguese translation.
Fixed:
- minor spelling error.

Fixed pt-BR language

---

src/pt-BR/validation.php

Translation for the dimension value missing in the pt-BR translation

Dimension value for pt-BR

---

src/he/validation.php

I think we can create a list of translator in each language that will be pinged when new translation is added, I would love to get pinged for hebrew translation

hebrew translation of validation dimensions

---

src/lt/validation.php

Updated validation.php for Lithuanian language with validation.dimensions translation.

Updated validation.php for Lithuanian language

---

src/pt-BR/validation.php

Simple translation for the file validation...

File translation for pt-BR

---

src/de/validation.php
src/nl/validation.php
todo.md

[nl] [de] Add translation for validation:file

---

src/de/validation.php

Hi!
In order to have a sensitive default translation for any failed login attempt (e.g. 'username is required' or 'password is required'), I added the commited attributes.

Added translation for login attributes

---

src/sv/validation.php

It said "Must have at least :digits digits" instead of "Must have :digits digits"

Corrected Swedish wording

---

src/ru/validation.php
todo.md

translated ru validation: uploaded

---

src/pt/validation.php

The uploaded validation to Portuguese.

upload validation rule

---

src/it/validation.php

bugfix: the "file" key value is still in English

[it] Update "file" key in validation.php 

---

src/zh-HK/validation.php
src/zh-TW/validation.php

update email validation fields of Traditional Chinese languages.

"email" fields for HK and TW 

---

src/da/validation.php

I just found a few missing translations for the Danish validation.

Update the Danish translations

---

script/todo.php
src/de/auth.php
src/de/pagination.php
src/de/passwords.php
src/de/validation.php

Just a fix for some inconsistencies in the german translation.
+ php-cs-fixer

[de] Fixed german translation

---

.php_cs

Fixes #571

---

src/zh-CN/validation.php
src/zh-HK/validation.php
src/zh-TW/validation.php
todo.md

Improve and Adding missing zh-* translation

---

todo.md

after_or_equal and before_or_equal done

All done for pt

---

src/de/validation.php
todo.md

Added translation for 'uploaded' in german

[de] uploaded

---

src/sv/passwords.php

Improved wording

---

src/pt-BR/validation.php

[pt-BR] Added custom validation attributes

---

src/tj/auth.php
src/tj/pagination.php
src/tj/passwords.php
src/tj/validation.php

[tj] New language

---

src/pt-BR/validation.php

Minor type in the translation of the "day" word.

Update pt-br validation.php

---

src/ca/validation.php

Common attributes traduced in 'ca'

Added common used atributes

---

src/tr/auth.php

Improved problems with plural and possessive forms.

Improved translation.

---

src/ar/validation.php

translate `before_or_equal` date item.

translate 'before_or_equal' date item

---

src/zh-CN/validation.php
src/zh-HK/validation.php
src/zh-TW/validation.php

https://github.com/laravel/laravel/commit/7e5739d266bba4624f933f547f111ee6ad26e095

Add IPv4/IPv6 validation messages.

---

src/ja/validation.php

translate ipv4 and ipv6 into japanese

---

src/de/validation.php
todo.md

Translated the new messages for IPv4/6 validation to German.

Translated IPv4/6 messages to German

---

src/es/validation.php

IPv4 and IPv6 messages in Spanish

Update validation.php (es)

---

src/es/validation.php

Añado artículo a la frase y quito 'contraseña'  en minúscula como primera palabra.

[ES] Update validation for password with min caracteres

---

src/pt-BR/validation.php
src/pt/validation.php

[PT/PT-BR] Translations for IPv4 and IPv6 validation

---

Source.md

I had changed my github username :)

Update contributor github link

---

src/it/validation.php
todo.md

Translated ipv4 and ipv6 validation rule

[it] update ipv4 ipv6 validation

---

src/nl/auth.php

See: https://onzetaal.nl/taaladvies/teveel-te-veel

Use correct grammar in Dutch translation

---

src/id/validation.php

There is something changed with original source, this make also need to change with the translation, see it on https://github.com/laravel/laravel/commit/90886732cf6df6d8694287c3f9d92496a4f1c61b#diff-9c04f727a922ad4f105b9ad764ec221d

Fix 'filled' validation message

---

src/pt-BR/validation.php

Very common word used in forms, for example, `textareas`

[PT-BR] Update validation.php with text attribute

---

src/sl/auth.php

File was a placeholder, copied from English.

Initial translation

---

src/id/passwords.php

some of the use of language is less in accordance with KBBI (Kamus Besar Bahasa Indonesia) rules.

update BAHASA in password

---

src/id/pagination.php

edit typo lang

---

src/eu/auth.php
src/eu/pagination.php
src/eu/passwords.php
src/eu/validation.php

[eu] New language

---

src/de/auth.php

The german translation was not really clearifiying, that the combination was not found.
With the current translation it looks like the data is not existing in the database.

Fixed german translation

---

src/lt/validation.php

Misspelling in word 'veikasis'. It must be 'sveikasis'.

updated validation.php

---

src/lv/auth.php
src/lv/pagination.php
src/lv/passwords.php
src/lv/validation

This one is translated by a relation not by me.

Adding Latvia (lv)

---

src/ug/auth.php
src/ug/pagination.php
src/ug/passwords.php
src/ug/validation.php

Uyghur language
list of ISO 639-1 codes: 'ug'

add Uyghur language

---

src/uz-cyrillic/auth.php
src/uz-cyrillic/pagination.php
src/uz-cyrillic/passwords.php
src/uz-cyrillic/validation.php
src/uz-latin/auth.php
src/uz-latin/pagination.php
src/uz-latin/passwords.php
src/uz-latin/validation.php

Added Uzbek language with latin and cyrillic versions.

[UZ] new language

---

src/ko/validation.php

[ko] Update regex validation

---

src/az/auth.php
src/az/pagination.php
src/az/passwords.php
src/az/validation.php

I did this pull request to include the work of @themahabbat

feature: add Azerbaijani (az ) version

---

src/fa/validation.php

this is my first pull request 😄 
i'll work on `fa` language and help to make it perfect.

not_regex translated and province attribute added

---

todo.md

Remove [Ar] todo which already translated

---

todo.md

See commit #01526d77dba68ff6db90e98fd2650bac871d8d18 & https://github.com/caouecs/Laravel-lang/pull/844

Updated todo list

---

json/id.json
todo.md

Please allow me to help translating `id.json` file which have not exist yet. I also updated the `todo.md`, remove todo items in `id` section.
Thanks.

Translated id.json

---

README.md

Added mention of the package in the README file.
This pull request based on merged #873 PR.

Added suggested package in "Project based" block in README.md

---

json/de.json
todo.md

This adds the missing json strings for the German language files.

[de] add missing json strings

---

json/id.json

I see some indonesian translation is not good enough (some dictions is incorret). This pull request will fix that.

Fix some translation errors in indonesian

---

json/zh-TW.json

Modify Unauthorized text,
Add servers wrong text (code 500).

Update language zh-TW

---

script/en/validation.php
src/it/validation.php

Fixed required_with_all message like Laravel 5.7: https://github.com/laravel/laravel/commit/4b589c1a4a5ec04838408875fc3bd233dbcf5904#diff-9c04f727a922ad4f105b9ad764ec221d
Fixed message also for Italian.

Fixed required_with_all message

---

script/en/en.json

Added "Verify Email Address". This is used for the subject in the verify-mail

Added "Verify Email Address"

---

json/ru.json

[Resolved conversation](https://github.com/caouecs/Laravel-lang/pull/936/files/933b91bc60b73efee6cef40b452b3850f08d2c99#diff-20f8f8ce31d7dd423d79190b4bad22b3R42) in #936
I incorrectly translated the word "verify". Instead, I write "check".
This pull request fixes a bug.

[ru] Fixed grammatical error

---

json/zh-TW.json

Update zh-TW.json
modify email text

Update language zh-TW 

---

json/ko.json

Typically, "ID 저장" is simply used to store the ID(cookie).
"로그인 상태 유지" is more accurate because Laravel's Remember Me is a feature that keeps logged in.

[KO] Fixed translation error

---

json/fr.json

There's a spelling mistake for the french, I fixed it.

[fr] Spelling mistake

---

json/es.json

This will match the value for the email from the `validation.php` file and the `es.json` file.

Match e-mail translation between json and validation files

---

json/zh-CN.json

new translations

---

src/de/passwords.php

Laravel 5.8: Minimum password length

---

src/de-CH/passwords.php

Laravel 5.8: DE-CH Minimum password length

---

json/ru.json
todo.md

[ru] Translated "This password reset link will expire in :count minutes."

[ru] Translated "This password reset link will expire in :count m"

---

json/de.json
todo.md

[de] Translated "This password reset link will expire in :count minutes"
For the #1022 PR.

[de] Translated "This password reset link will expire in :count m"

---

src/nb/passwords.php
src/nn/passwords.php

[nb and nn] - Update password char count from six to eight

---

README.md

See #1055 
This PR to `master` branch.

Changes to implement #1055 for Laravel 5.1-5.7

---

README.md

See #1055 
This PR to `laravel58` branch.

Changes to implement #1055 for Laravel 5.8

---

script/en/validation.php
src/zh-CN/validation.php
src/zh-HK/validation.php
src/zh-TW/validation.php
todo.md

* Add ends_with attribute to en/validation.php
* Add ends_with attribute to zh-CN/validation.php
* Add ends_with attribute to zh-HK/validation.php
* Add ends_with attribute to zh-TW/validation.php
See [Laravel #5020](https://github.com/laravel/laravel/commit/93c687418963f7c99b641fda905015054c785eb4)

[zh-*, en] Add ends_with attribute to validation.php

---

src/fa/validation.php

Add ends_with

---

README.md
src/ru/validation.php
src/zh-TW/validation.php
todo.md

Patch to migrate laravel58 to master branch

---

README.md

Just waiting for the release of the new version 😊

Added information about version 6

---

src/pt-BR/validation.php

Changed the pt-br 'remember' validation message.

Update pt-br validation message

---

src/de-CH/validation.php
todo.md

* validation : date_equals
* validation : ends_with
* validation : starts_with
* validation : uuid

Add missing translations for de-CH

---

json/th.json

[TH] Correctly Thai language

---

json/zh-CN.json
json/zh-HK.json
json/zh-TW.json
script/en/en.json
script/en/validation.php
src/zh-CN/validation.php
src/zh-HK/validation.php
src/zh-TW/validation.php
todo.md

* Add `password` attribute to [zh-*, en]/validation.php
* Add `Please confirm your password before continuing.` and `We won\'t ask for your password again for a few hours.` text to [zh-*, en].json
See [Larael#5129](https://github.com/laravel/laravel/pull/5129/files#diff-9c04f727a922ad4f105b9ad764ec221dR96) and [Laravel/ui#34](https://github.com/laravel/ui/pull/34/files#diff-a3b930c58634f665af7863599281d23cR11-R12)

[zh-*, en] Add password confirm text

---

src/nl/validation.php

Adds password translation, new in Laravel 6.2 (laravel/laravel@050c1d8)

Added password translation L6.2

---

src/fr/validation.php

https://github.com/laravel/laravel/commit/050c1d880ec1d48ef40d7a0f2b2f1040c23cebb9#diff-9c04f727a922ad4f105b9ad764ec221d

Add french translation for password validation

---

src/es/passwords.php

Adding the throttled validation field, created for Laravel 6.

[es] Adding new field (throttled) for Laravel 6

---

src/zh-CN/validation.php
src/zh-HK/validation.php
src/zh-TW/validation.php

Optimize the string to make `starts_with` and `ends_with` symmetrical.

[zh-*] Optimize string starts_with, ends_with

---

json/nl.json

Nothing really special, just two typos.

Fix typos in Dutch translation

---

composer.json
script/todo.php
todo.md

Improved todo.md page + refactored todo.php

---

json/tr.json

I forgot a sentence to change.

Tr typo fix

---

script/en/passwords.php
src/fil/passwords.php

@see https://github.com/laravel/laravel/commit/ffc74ba143a7de4a89f2c3fd525a5621ca879e38

Removed hyphen on email

---

src/sv/validation.php

https://github.com/laravel/laravel/commit/050c1d8

[sv] Added password translation for Laravel 6.2

---

json/tr.json
src/tr/validation.php
todo.md

I've noticed there are things missing in tr.json and other tr related sources

Turkish language 

---

README.md

They plan to release a new version in early March.

Added mention of Laravel 7

---

src/ar/validation.php

replace tilde with the indefinite marker of tanween with fatHah

fix typo in validation file - AR

---

src/de-CH/passwords.php
todo.md

Translate passwords.throttled for de-CH and update the todo file

[de-CH] update password validation

---

src/fr/passwords.php

Better translation ! Previous wasn't really correct :)

Update french passwords.throttled

---

src/hr/validation.php

Hey @caouecs,  
adding a minor change to the Croatian localization. The custom message was not translated.  
Kind regards,
g

Update HR validation.php

---

json/fr.json

These adds are related to 2 new localizable strings in `laravel/ui` introduced by laravel/ui#105

[fr] Update missing messages

---

json/pl.json
todo.md

Polish should already be completely translated :)

[PL] Translate the new phrases

---

json/pt-BR.json
todo.md

[pt-BR] update dashboard

---

json/es.json

The file es.json has a structure error, it has a comma in the last line.

Error parse "es.json"

---

README.md

Updated appearance of package manager links

---

json/ru.json
script/en/en.json

See https://github.com/laravel/jetstream/blob/1.x/stubs/livewire/resources/views/profile/delete-user-form.blade.php#L28
The todo file was not generated because this can create a conflict with other PRs.

[en, ru] Added missing translation key

---

json/pl.json
todo.md

ps. the word "Email" is spelled the same in Polish
ps2. Hope it's ok now, thanks @andrey-helldar

Translate for PL

---

CONTRIBUTING.md

I considered pertinent to add documentation about of the new feature of exclude translations.

Add documentation about of exclude translations feature in CONTRIBUTING.md

---

.github/workflows/make-todo.yml

Fix for #1401
https://github.com/andrey-helldar/Laravel-lang/actions/runs/294023748

Fixed test execution error with no changes

---

.github/ISSUE_TEMPLATE/1_Bug_report.md
.github/ISSUE_TEMPLATE/config.yml

See https://github.com/laravel/framework/tree/master/.github and https://github.com/laravel/framework/issues/new/choose

Added template preset like laravel/framework

---

script/todo.php

I deleted the old branch and created a new one after updating original:master

fixed 1377 - ignores the additional information

---

src/es/validation.php

Add `multiple_of` Spanish translation to validation.php
https://github.com/laravel/laravel/pull/5449

[es] Add field to validation.php

---

json/pt_BR.json

Added missing Brasilian Portuguese translations.

Update pt_Br.json added missing translations

---

script/excludes/es.php
src/es/validation-inline.php

Added missing translation for `validation-inline` and added an exclusion

[es] Complete translations

---

src/pl/validation-inline.php
src/pl/validation.php
todo.md

[PL] new missing translations

---

json/es.json
script/en/en.json

Taylor has updated this translation
[profile/logout-other-browser-sessions-form.blade.php](https://github.com/laravel/jetstream/commit/055be8529b4fb45897e9d5ef42eee0b2a45c8bde)

[en, es] Update wording translation

---

json/nl.json

Previous it was "Remember **Me**" and in Livewire it is "Remember **me**"

"Remember me" for Livewire support

---

json/ru.json

For https://github.com/laravel/jetstream/commit/055be8529b4fb45897e9d5ef42eee0b2a45c8bde

[ru] Jetstream key changed (Some of your recent sessions are listed below...)

---

script/en/auth.php
src/es/auth.php

https://github.com/laravel/laravel/blob/8.x/resources/lang/en/auth.php#L17
New tag added to `auth.php`

[en, es] Add new tag in auth.php

---

json/fr.json

Fixes a small conjugation mistake.

[fr] Fixes small mistakes

---

src/es/passwords.php

Translations have been slightly modified in order to follow the same formal pattern of translations in other files.

Updated passwords.php

---

json/es.json
script/en/en.json

This translation is used by [Laravel Breeze](https://github.com/laravel/breeze).
* [This is a secure area of the application. Please confirm your password before continuing.](https://github.com/laravel/breeze/blob/1.x/stubs/resources/views/auth/confirm-password.blade.php#L10)

[en, es] Add new tag used in Laravel Breeze

---

json/it.json
src/it/auth.php

Added:
- password in auth.php
- "This is a secure area of the application. Please confirm your password before continuing." in it.json

Updated italian translations

---

json/es.json
script/en/en.json

This modification was ready as of January 6 and had been ignored
- [Cancel](https://github.com/laravel/jetstream/blob/2.x/stubs/livewire/resources/views/teams/team-member-manager.blade.php#L102)

[en, es] Translate cancel button of team invitation

---

src/de/validation.php

Add missing custom validation attribute 'current_password'.
Used by Fortify UpdateUserPassword (/app/Actions/Fortify/UpdateUserPassword.php), see https://github.com/laravel/fortify/blob/1.x/stubs/UpdateUserPassword.php
Every language lacks this attribute.

[de] missing custom validation attribute

---

src/ru/validation.php

Add translate for `validation.attributes.current_password`.
This attribute is used in the **Update Password** form of the `/user/profile` route from the `laravel/fortify` package.

[ru] Add translate for `current_password`

---

src/es/validation.php

This translation is used by Laravel Fortify validator in [UpdateUserPassword](https://github.com/laravel/fortify/blob/1.x/stubs/UpdateUserPassword.php#L23)

[es] Add validation.attributes.current_password translation 

---

src/fa/validation.php

Update fa validation
add district, area and national_code

add district,area and national_code

---

src/pt/auth.php
src/pt_BR/auth.php

Updated translations for pt and pt_BR

[pt, pt_BR] Updated translations

---

app/tests/JsonTest.php
app/tests/PhpTest.php
app/tests/TestCase.php
app/tests/TodoLocalesTest.php
app/tests/TodoTest.php

Updated tests

---

app/main/Concerns/Excludeable.php
app/main/Processors/Todo/Processor.php

Fixed Todo Script : problem of comparaison

---

_config.yml
docs/_config.yml
docs/index.md

PS: I did not explicitly specify the description - GitHub Pages automatically takes it from the description of the repository:

Minor edits for documentation on GitHub Pages

---

docs/contributing-to-dev.md

I added some clarification in contributing docs about `validation-online.php`

Update contributing docs. Clarification about validation-online

---

app/tests/Concerns/Messages.php
app/tests/JsonTest.php
app/tests/PhpTest.php
app/tests/TestCase.php
src/oc/validation-inline.php
src/pl/validation-inline.php

Added validation for the `:attribute` string in the `validation-inline.php` files

---

.github/workflows/self-update.yml
README.md
app/main/Concerns/Storable.php
app/main/Constants/Referents.php
app/main/Constants/Resource.php
app/main/Contracts/Filesystem.php
app/main/Processors/Processor.php
app/main/Processors/Referents.php
app/main/Processors/Statuses/Locales.php
app/main/Processors/Statuses/Main.php
app/main/Processors/Statuses/Processor.php
app/main/Services/Compilers/Referents.php
app/main/Services/Filesystem/Base.php
app/main/Services/Filesystem/Json.php
app/main/Services/Filesystem/Markdown.php
app/main/Services/Filesystem/Php.php
app/referents.php
app/resources/referents.stub
app/tests/Concerns/Messages.php
app/tests/JsonTest.php
app/tests/PhpTest.php
app/tests/TestCase.php
docs/referents.md
src/oc/validation-inline.php
src/pl/validation-inline.php

Added auto-update `docs/referents.md` file

---

README.md
docs/index.md

`Projects based on this package` title renamed to `Translation managers`

---

app/main/Concerns/Countable.php
app/main/Processors/Statuses/Main.php
app/main/Processors/Statuses/Processor.php
app/main/Services/Compilers/Compiler.php
app/main/Services/Compilers/Status.php
app/main/Services/Counter.php
app/resources/status.stub
docs/status.md

**Before:**
**After:**
PS: I just wanted to do 😊

Adding a percentage of translations

---

locales/hy/hy.json

https://github.com/Laravel-Lang/lang/pull/1688

[hy] Fixed missing key

---

app/main/Facades/Arr.php
app/main/Helpers/Arr.php
app/main/Processors/Statuses/Processor.php

For https://github.com/Laravel-Lang/lang/issues/1714

Added comparison of sub-elements of arrays

---

locales/ru/packages/nova.json
source/packages/nova.json

Hola!
The Nova release v3.25.0 brings new line for translations

Add new translation for Nova

---

excludes/tr.php

I forgot to add this to the previous PR. :/

[tr] Completed missing translation

---

locales/ms/auth.php

Stumbled upon a missing Malay translation. Cheers.

Add missing Malay translation

---

locales/es/es.json
source/en.json

Small changes in Laravel that affect our translations
- https://github.com/laravel/framework/pull/37709/files
The keys that are becoming obsolete should be removed in future versions of this package, we already have several, [among them](https://github.com/Laravel-Lang/lang/blob/master/source/en.json#L9-L11):
- If you’re having trouble clicking the \":actionText\" button, copy and paste the URL below\ninto your web browser:
- Login
- Logout

[en, es] Remove non ASCII apostrophe from email notification.

---

locales/cs/cs.json

[cs] Logout typo fixed

---

app/main/Constants/Referents.php

adding user Olsza (me) to the referents list for PL

add Referent Olsza for PL

---

locales/pl/pl.json

I missed one sentence to be translated, ie "Currently Subscribed"

added translation of one lost sheep in PL ;)

---

locales/es/validation-inline.php
locales/es/validation.php
source/validation-inline.php
source/validation.php

This PR is related to:
- https://github.com/laravel/laravel/pull/5636
- https://github.com/laravel/laravel/pull/5637

[en, es] Update validation.php

---

locales/es/es.json
source/packages/jetstream.json

[https://github.com/laravel/jetstream/blob/2.x/src/Http/Controllers/Inertia/CurrentUserController.php#L31](https://github.com/laravel/jetstream/blob/2.x/src/Http/Controllers/Inertia/CurrentUserController.php#L31)

[en, es] Jetstream new tag: The password is incorrect.

---

excludes/id.php

[id] Add exclude key

---

locales/ka/validation.php

This word is incorrectly written. It's not grammatical mistake, just wrong writing.

Incorrect word update [ka]

---

locales/id/id.json
locales/id/validation-inline.php
locales/id/validation.php

1. Fixed missed translation for 'accepted_if' in validation-inline.php
2. Fixed missed translation for 'accepted_if' in validation.php
3. Fixed missed 'The password is incorrect.' and 'Total:' in id.json

[id] Fixed missing translation

---

locales/de/de.json

Fixed missing `The password is incorrect.` translation

[de] Fixed missing translation

---

locales/de/validation-inline.php
locales/de/validation.php
source/validation-inline.php
source/validation.php

add `prohibits` to source/validation.php and source/validation-inline.php and translate into German
see https://github.com/laravel/laravel/pull/5681

add new `prohibits` validation

---

README.md

Live: https://github.com/andrey-helldar/Laravel-lang/tree/patch/2021-12-02/17-52#readme
Screenshot:

Just a beautiful preview 😊

---

locales/pl/pl.json

this key "E-Mail Address" is used eg. in laravel/ui generated forms view

added missing key for pl: E-Mail Address

---

locales/fa/validation-nova-inline.php

From https://github.com/Laravel-Lang/lang/pull/1932

[fa] `attached` key moved to Nova inline file

---

composer.json

Normalize the  `composer.json` file with [ergebnis/composer-normalize](https://github.com/ergebnis/composer-normalize)

Normalize `composer.json`

---

locales/id/validation.php

This is the missing translation

[ID] Added missing translation

---

locales/ar/ar.json

Phrase: **This coupon code can only be used by new customers**

[ar] Translate the new key

---

locales/de/de.json

Translate "This coupon code can only be used by new customers."

[de] Missing German translation

---

locales/fr/fr.json

Ajout des traductions manquantes

fix(fr): missing translations

---

locales/de/de.json

Added translation for key "An error occurred while uploading the file."

Update de.json add "An error occurred while uploading the file."

---

locales/fr/validation.php

The Following french translations are malformed, this PR fixes that

[fr] Fix malformed french translations

---

app/main/Constants/Referents.php
locales/fr/fr.json

Ajout des traductions manquantes

[fr] missing translations

---

locales/de/php.json

[de]: Add translations

---

locales/ja/php-inline.json

[ja] add translation

---

locales/ja/php.json

I think this word is not user friendly.

[ja]: Fix translation

---

locales/ru/json.json

@Laravel-Lang/laravel-lang, hey!
A new key has been added to the project: https://github.com/Laravel-Lang/lang/commit/9e6e683627b4d3f315078d59561bf4ddaf96b142

[ru]: Added translation of Fortify

---

locales/sw/json.json

Translation of added keyword: "The provided two factor recovery code was invalid."

[sw]: Translation of added keyword(s)

---

locales/sw/json.json

[sw]: Translation of added keywords

---

locales/ja/json.json

[ja] update translation

---

locales/ja/php-inline.json
locales/ja/php.json

[ja] translate new key

---

locales/az/php.json
locales/tr/php.json

[az, tr]: Translations update

---

locales/fa/json.json

[fa]: Add new key

---

locales/sw/php-inline.json
locales/sw/php.json

I have translated the newly added keywords from #2467

[sw]: Translation of added keywords (for added keywords from 9.x keys)

---

locales/sw/json.json

Translated added keyword "Payment Required"

[sw]: Translation of added keyword

---

source/nova/4.x/nova.json

@Laravel-Lang/laravel-lang, hi! New keys here.

[source]: Added Laravel Nova's keys

---

locales/es/php.json

Replace 'The' with 'El' on 'in' message

[es]: Translation error

---

locales/nl/json.json

Fixes https://github.com/Laravel-Lang/lang/pull/3170#discussion_r1175126032

[nl] Fix spelling error

---

locales/ja/php.json

パスワードをリセットしました。 => I have reset my password.
パスワードが再設定されました。 => Your password has been reset.

[ja]: Translation fix

---

locales/zh_CN/json.json

Update locales/zh_CN/json.json

[zh_CN]: Update translations

---

locales/sw/json.json

I have translated the added keyword

[sw] Translation of added keyword

---

locales/it/json.json

fixed bad italian automatic translation :-)

[it]: Fix translation

---

locales/th/json-inline.json

Make the translation of the variations of a similar sentence (on letter/number/symbol combination requirements) looks consistent across.

[th]: Update json-inline.json

---

locales/bn/php.json

Updated the translation to its previous form. The previous one was right according to Grammer.

[bn]: Translation updated

---

locales/th/php-inline.json
locales/th/php.json

Updated Thai translation for the `required_if_declined` key.

[th]: Update translations

---

locales/ja/php-inline.json
locales/ja/php.json

[ja]: Refine translation

---

locales/cs/php.json

wrong parameter name in validation.max.file

[cs]: Update php.json

---

.github/workflows/download.yml
src/Plugin.php
src/Plugins/Nova/V5.php

[source]: Added Laravel Nova 5 support

---

locales/it/json.json

[it]: Fixed typo in italian json

---

locales/ja/json.json

In japanese, auxiliary verb of may contains hope or infer.
So i correct it.
I hope this fix helps.

[ja]: Correcting of the meaning of the Japanese translation

---

locales/ja/json.json

[ja]: Update translation

---

locales/ja/json.json

I'm so sorry for making trouble for you.
I ran into a minor problem during conflict resolution, so I decided to create a new branch and renew this PR.
Thank you for your understanding.

[ja]: fix translate japanese kanji

---

locales/ro/json.json

[ro]: Update `json.json` translations

---

locales/nb/_excludes.json
locales/nb/json.json

Added missing translations and added Type to ignore.

[nb]: Added missing and added excludes

---

locales/ko/php-inline.json
locales/ko/php.json

[ko] translated from Laravel-Lang/lang#6861

[ko]: translated from Laravel-Lang/lang#6861

---

locales/ja/json.json

I hope this fix will helps !
```
Before オーストラア
```
```
After オーストラリア
```

[ja]: Fix Typo

---

.github/workflows/download.yml

Removed setup for Git and Composer, and updated PHP code-style step.

[app]: Refactor workflow by removing unnecessary steps
